### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by aiNeu0taip9ue**
```
docker build . -t quark
```

Examples:
```
docker run -v $(pwd):/tmp -it quark bash
quark -a /tmp/ThaiCamera.apk -r rules/ --summary
```
```
docker run -v $(pwd):/tmp -it quark quark -a /tmp/ThaiCamera.apk -r rules/ --summary
```

### CODE REVIEW

**Comment by krnick** [comment]
Hello @aiNeu0taip9ue ,Thank you for your contribution
using docker for analysis is a great idea to me. Jus make a test and using following example, good work!

`docker run -v $(pwd):/tmp -it quark quark -a sample/14d9f1a92dd984d6040cc41ed06e273e.apk -r  rules/ -s`

**Comment by sidra-asa** [comment]
@aiNeu0taip9ue  Thanks for the enhancement. Please add more documentation in README.md and docs in this PR. It's really a great work.

**Comment by 18z** [comment]
@aiNeu0taip9ue Nice work!

**Comment by krnick** [comment]
@aiNeu0taip9ue LGTM, thanks

**Pull request merged**
