### PR TITLE
Add Quark Script to detect CWE-780

### PR DESCRIPTION
**Pull request by haeter525**
# Detect CWE-780 in Android Application (MSTG-Android-Java.apk)

This scenario seeks to find **the use of the RSA algorithm without Optimal Asymmetric Encryption Padding (OAEP)**. See [CWE-780](https://cwe.mitre.org/data/definitions/780.html) for more details.

Let’s use this [APK](https://github.com/OWASP/MASTG-Hacking-Playground) and the above APIs to show how the Quark script finds this vulnerability.

We first design a detection rule `useCryptographicAlgo.json` to spot on behavior using the cryptographic algorithm. Then, we use API `behaviorInstance.hasString(pattern, isRegex)` to filter behaviors using the RSA algorithm. Finally, we use the same API to check if the algorithm runs without the OAEP scheme. If the answer is YES, the plaintext is predictable.

### behaviorInstance.hasString(pattern, isRegex)
* Description: Check if the arguments of the two APIs contain the string.
* params: 
    1. `pattern` : string that may appear in the arguments
    2. `isRegex` : consider the string as a regular expression if True, defaults to False
* return: the matched string

## Quark Script CWE-780.py
```python=
from quark.script import Rule, runQuarkAnalysis

SAMPLE_PATH = "MSTG-Android-Java.apk"
RULE_PATH = "useCryptographicAlgo.json"

ruleInstance = Rule(RULE_PATH)
quarkResult = runQuarkAnalysis(SAMPLE_PATH, ruleInstance)

for useCryptographicAlgo in quarkResult.behaviorOccurList:

    methodCaller = useCryptographicAlgo.methodCaller

    if useCryptographicAlgo.hasString("RSA") and \
        not useCryptographicAlgo.hasString("OAEP"):
        print(f"CWE-780 is detected in method, {methodCaller.fullName}")
```
 
## Quark Rule useCryptographicAlgo.json
```JSON
{
    "crime": "Use of cryptographic algorithm",
    "permission": [],
    "api": [
        {
            "class": "Ljavax/crypto/Cipher;",
            "method": "getInstance",
            "descriptor": "(Ljava/lang/String; Ljava/lang/String;)Ljavax/crypto/Cipher"
        },
        {
            "class": "Ljavax/crypto/Cipher;",
            "method": "init",
            "descriptor": "(I Ljava/security/Key;)V"
        }
    ],
    "score": 1,
    "label": []
}

```

### Quark Script Result

```bash
$ python3 CWE-780.py
CWE-780 is detected in method, Lsg/vp/owasp_mobile/OMTG_Android/OMTG_DATAST_001_KeyStore; encryptString (Ljava/lang/String;)V
```

### CODE REVIEW

**Comment by zinwang** [comment]
@18z Please review the docs about CWE-780 detection. 

[docs/source/quark_script.rst](https://github.com/quark-engine/quark-engine/pull/399/files#diff-7744b29440ac1ab240404c0cde1ea167545bc9b7bda2a26078a15921939600de)

Thank you!

**Comment by 18z** [comment]
Hi @haeter525 

Thank you for the great work!
I think we can use ```Algo``` to replace ```Algorithm```. 

This is the explanation in Cambridge Dicrtionary.

>Short for algorithm : a set of mathematical instructions or rules that, especially if given to a computer, will help to calculate an answer to a problem.

```python
from quark.script import Rule, runQuarkAnalysis

SAMPLE_PATH = "MSTG-Android-Java.apk"
RULE_PATH = "useOfCryptographicAlgo.json"

ruleInstance = Rule(RULE_PATH)
quarkResult = runQuarkAnalysis(SAMPLE_PATH, ruleInstance)

for useCryptographicAlgo in quarkResult.behaviorOccurList:

    methodCaller = useCryptographicAlgo.methodCaller

    if useCryptographicAlgo.hasString("RSA") and \
        not useCryptographicAlgo.hasString("OAEP"):
        print(f"CWE-780 is detected in method, {methodCaller.fullName}")
```

**Comment by haeter525** [comment]
Hi @18z .
I've updated the document. Please take a look. Thanks!

**Review by 18z — APPROVED** [review]

**Comment by 18z** [comment]
> Hi @18z . I've updated the document. Please take a look. Thanks!

Thank you @haeter525 , I've done my part of the review. I have no further questions.

**Review by zinwang — APPROVED** [review]
@haeter525 The Quark Script works well!
I have no questions. Thanks for the work!

**Comment by zinwang** [comment]
LGTM! Merge!

**Pull request merged**
