### PR TITLE
Doc update for Directory Scanning

### PR DESCRIPTION
**Pull request by lordlabuckdas**
* Added example Python and Bash code scanning directories
* Added link to `integration.html` for directory scanning after **Usage** in `install.html`

Helps with #92.

I couldn't find a `doc` branch as mentioned in the documentation, so I'm creating a PR to `master`, please let me know if that will be an issue.

### CODE REVIEW

**Comment by krnick** [comment]
Thank you @lordlabuckdas , I have tested all these example code, and everything works very well.

Some content could be adjusted to be better:

The `-d` option can be removed since the `-o` option can perform all analysis.
```
quark -a ${apkFile} -d -o ${apkFile%%.*}_output.json;
```


Fix some words:
To run quark scans for an entire directory, a simple bash script can be used. -> To scan the entire directory with quark, you can use a simple bash script.

To know how to run scans for a directory, please have a look at. -> To learn how to scan multiple samples in a directory, please have a look at.

Thank you again for making our doc more complete 😄

**Comment by 18z** [comment]
@lordlabuckdas 

Interested in this? 😃 

https://www.honeynet.org/gsoc/gsoc-2021/google-summer-of-code-2021-project-ideas/

**Comment by lordlabuckdas** [comment]
Sorry for the poor phrasing, @krnick, I've fixed it now. 😅

Yes, I'm interested in GSoC, @18z! I'm currently going through Quark Engine's code base, I plan to contribute to this repo and help in the completion of some ideas. 😄

Glad to be of help!

**Comment by 18z** [comment]
> Sorry for the poor phrasing, @krnick, I've fixed it now. 😅
> 
> Yes, I'm interested in GSoC, @18z! I'm currently going through Quark Engine's code base, I plan to contribute to this repo and help in the completion of some ideas. 😄
> 
> Glad to be of help!

@lordlabuckdas awesome, welcome and feel free to discuss with us! 😸

**Comment by krnick** [comment]
LGTM, thank you @lordlabuckdas for your kind help!

**Pull request merged**
