### PR TITLE
[#444] Adjust CWE Show Case format in README.md.

### PR DESCRIPTION
**Pull request by PoJenC**
# CWE Showcases
*   [CWE-020](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-20-in-android-application-diva-apk)  Improper Input Validation 
*   [CWE-089](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-89-in-android-application-androgoat-apk)  Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection') 
*   [CWE-094](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-94-in-android-application-ovaa-apk)  Improper Control of Generation of Code ('Code Injection') 
*   [CWE-312](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-312-in-android-application-ovaa-apk)  Cleartext Storage of Sensitive Information 
*   [CWE-319](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-319-in-android-application-ovaa-apk)  Cleartext Transmission of Sensitive Information 
*   [CWE-327](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-327-in-android-application-injuredandroid-apk)  Use of a Broken or Risky Cryptographic Algorithm 
*   [CWE-532](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-532-in-android-application-dvba-apk)  Insertion of Sensitive Information into Log File 
*   [CWE-749](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-749-in-android-application-mstg-android-java-apk)  Exposed Dangerous Method or Function 
*   [CWE-780](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-780-in-android-application-mstg-android-java-apk)  Use of RSA Algorithm without OAEP 
*   [CWE-798](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-798-in-android-application-ovaa-apk)  Use of Hard-coded Credentials 
*   [CWE-921](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-921-in-android-application-ovaa-apk)  Storage of Sensitive Data in a Mechanism without Access Control 
*   [CWE-926](https://quark-engine.readthedocs.io/en/latest/quark_script.html#detect-cwe-926-in-android-application-dvba-apk)  Improper Export of Android Application Components

### CODE REVIEW

**Comment by sidra-asa** [comment]
@PoJenC 

It looks like the new format is a list, not a table.
If the expected format is a table, please correct either the commits or description of this PR.

**Comment by sidra-asa** [comment]
@PoJenC 

I also found that there are some issues in Codacy Static Code Analysis.
Please follow the suggestions in the [details](https://app.codacy.com/gh/quark-engine/quark-engine/pullRequest?prid=10847314).

**Comment by sidra-asa** [comment]
@PoJenC 

Could you also post a screenshot of revised CWE Show Case in the PR description ?

**Comment by PoJenC** [comment]
> @PoJenC
> 
> It looks like the new format is a list, not a table. If the expected format is a table, please correct either the commits or description of this PR.

**Comment by PoJenC** [comment]
Hi @sidra-asa ,
1. The space issue that Codacy indicated is fixed. Thanks.
2. The list format of markdown is easier to maintain than the table format, and it's clearer for reading.

**Review by sidra-asa — APPROVED** [review]
LGTM. 

@18z  Do you approve it?

**Review by 18z — APPROVED** [review]

**Comment by 18z** [comment]
LGTM, @18z approves this PR.

**Pull request merged**
