### PR TITLE
Add method reference for show_rule_classification in the document

### PR DESCRIPTION
**Pull request by LiangPPP**
show_rule_classification
===============================

**The algorithm of show_rule_classification**

The function ``show_rule_classification`` extracts rule classification data, highlighting the links between parent functions and associated crimes. It then displays this data in table, JSON, and graphical formats.

Here is the process of ``show_rule_classification``.

```
1. Call the print_info function to display "Rules Classification".

2. Invoke the get_rule_classification_data function
    - Use self.quark_analysis.call_graph_analysis_list and MAX_SEARCH_LAYER as parameters.
    - Store the returned rule classification data in the data_bundle variable.

3. Call the output_parent_function_table function to display tables on the console. 
    - The first column of the table is "Parent Function", and the second column displays the name of that parent function. 
    - Subsequent rows list the "Crime Description" associated with that parent function.
   
4. Call the output_parent_function_json function to output a JSON file named "rules_classification.json".
    - The structure of the file is a list containing multiple dictionaries. Each dictionary has two keys: parent and crime. 
 
5. Call the output_parent_function_graph function to create a PNG format graphic file.
    - This graphic displays the reference relationships between parent functions and the crime descriptions associated with each parent function.
```

Here is the flowchart of ``show_rule_classification``.

**The code of show_rule_classification**

```python
def show_rule_classification(self):
    print_info("Rules Classification")

    data_bundle = get_rule_classification_data(
        self.quark_analysis.call_graph_analysis_list, MAX_SEARCH_LAYER
    )

    output_parent_function_table(data_bundle)
    output_parent_function_json(data_bundle)
    output_parent_function_graph(data_bundle)
```

### CODE REVIEW

**Comment by sidra-asa** [comment]
@LiangPPP 

Thank you for the new document.
However, it seems that description is not clear.
IMHO, it could specify more about what the ``show_rule_classification`` results are.

**Comment by sidra-asa** [comment]
There are some grammatical errors in the 4th and 5th of the process.
For example, it misses conjunction "to" between "function" and "output".

**Review by sidra-asa — APPROVED** [review]
LGTM

**Review by pulorsok — APPROVED** [review]
LGTM

**Pull request merged**
