### PR TITLE
Add interface and struct folders into Objects

### PR DESCRIPTION
**Pull request by haeter525**
**Description**

This PR aims to add two folders to keep the file structure of Quark as clean as it was before adding the standard interface.

Here are the new folders:

+ **quark/Object/interface** - a directory that holds standard interfaces of Quark. The interface defines how Quark interacts with its core library.
+ **quark/Object/struct** - a directory that holds data structures used by Quark. The data structures stores the data that Quark needs for analysis.

Base on the descriptions above, the Objects folder is arranged as below.

```
Objects
|-- __init__.py
|-- analysis.py
|-- apkinfo.py
|-- interface				<-- The fist folder
|   |-- __init__.py
|   `-- baseapkinfo.py			<-- Moved from Objects folder
|-- quark.py
|-- quarkrule.py
`-- struct				<-- The second folder
    |-- __init__.py
    |-- bytecodeobject.py		<-- Moved from Objects folder
    |-- methodobject.py			<-- Moved from Objects folder
    |-- registerobject.py		<-- Moved from Objects folder
    `-- tableobject.py			<-- Moved from Objects folder
```

**Test Plans**

- [x] Ensure the whole project passes all existing tests.

### CODE REVIEW

**Review by krnick — APPROVED** [review]
Awesome, thank you @haeter525 for the PR

**Comment by krnick** [comment]
Could you also move quarkrule.py into `struct/ruleobject.py`?

**Comment by haeter525** [comment]
@krnick Sure, I will work on it.

Also, I found two duplicated test files in `tests/quark/Objects`.
[test_ruleobject.py](https://github.com/quark-engine/quark-engine/blob/master/tests/Object/test_ruleobject.py) and [test_quarkrule.py](https://github.com/quark-engine/quark-engine/blob/master/tests/Object/test_quarkrule.py) are both for ruleobejct.py.
I recommend that we merge them into one.

What do you think?

**Comment by krnick** [comment]
> @krnick Sure, I will work on it.
> 
> Also, I found two duplicated test files in `tests/quark/Objects`.
> [test_ruleobject.py](https://github.com/quark-engine/quark-engine/blob/master/tests/Object/test_ruleobject.py) and [test_quarkrule.py](https://github.com/quark-engine/quark-engine/blob/master/tests/Object/test_quarkrule.py) are both for ruleobejct.py.
> I recommend that we merge them into one.
> 
> What do you think?

Sure thing!

**Comment by krnick** [comment]
LGTM, Nice work @haeter525

**Pull request merged**
